using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Dloizides.Analyzers.Rules;

internal static class CommentTrivia
{
    private static readonly string[] DirectivePrefixes = { "ReSharper", "<auto-generated", "@formatter:" };

    public static bool IsDoc(SyntaxTrivia trivia)
    {
        if (trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
            trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
            return true;
        var text = trivia.ToString();
        if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia))
            return text.StartsWith("///", StringComparison.Ordinal) && !text.StartsWith("////", StringComparison.Ordinal);
        if (trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            return text.StartsWith("/**", StringComparison.Ordinal) && !text.StartsWith("/**/", StringComparison.Ordinal);
        return false;
    }

    public static bool IsPlainComment(SyntaxTrivia trivia)
    {
        var isComment = trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia);
        return isComment && !IsDoc(trivia) && !IsDirective(trivia.ToString());
    }

    public static bool IsLayout(SyntaxTrivia trivia) =>
        trivia.IsKind(SyntaxKind.WhitespaceTrivia) || trivia.IsKind(SyntaxKind.EndOfLineTrivia);

    public static bool IsExcludedPath(string? path)
    {
        if (string.IsNullOrEmpty(path))
            return false;
        var normalized = path!.Replace('\\', '/');
        return normalized.IndexOf("/Migrations/", StringComparison.OrdinalIgnoreCase) >= 0 ||
               normalized.StartsWith("Migrations/", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsDirective(string text)
    {
        var body = text.TrimStart('/', '*', ' ', '\t');
        foreach (var prefix in DirectivePrefixes)
            if (body.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return true;
        return false;
    }
}
