using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Dloizides.Analyzers.Tests;

public class FeatureFolderAnalyzerTests
{
    private const string Dlz0005 = "DLZ0005";

    [Theory]
    [InlineData("Shop.Services")]
    [InlineData("Shop.Application.Helpers")]
    [InlineData("Shop.Utils.Text")]
    [InlineData("Shop.Utilities")]
    [InlineData("Common.Shop")]
    public async Task Analyze_WithTechnicalNamespaceSegment_ReportsDlz0005(string ns)
    {
        var ids = await AnalyzerRunner.IdsAsync($"namespace {ns} {{ public class Pricing {{ }} }}", assemblyName: "Shop.Api");

        Assert.Equal(new[] { Dlz0005 }, ids);
    }

    [Fact]
    public async Task Analyze_WithServicesNamespace_NamesTheSegmentAndTheRule()
    {
        var diagnostics = await AnalyzerRunner.RunAsync(
            "namespace Shop.Services { public class Pricing { } }", "Sample.cs", DocumentationMode.Parse, "Shop.Api");

        var message = Assert.Single(diagnostics).GetMessage();
        Assert.Equal("'Pricing' sits in the 'Services' namespace segment: organize by feature/use case (ARCH-VSA-1)", message);
    }

    [Fact]
    public async Task Analyze_WithTwoTypesAndNestedType_ReportsOncePerTopLevelType()
    {
        var source = "namespace Shop.Helpers.Common { public class A { public class Inner { } } public interface IB { } }";

        var ids = await AnalyzerRunner.IdsAsync(source, assemblyName: "Shop.Api");

        Assert.Equal(new[] { Dlz0005, Dlz0005 }, ids);
    }

    [Theory]
    [InlineData("Shop.Features.Checkout")]
    [InlineData("Shop.ServicesCatalog")]
    [InlineData("Shop.Commons")]
    [InlineData("Shop.services")]
    public async Task Analyze_WithFeatureNamespace_ReportsNothing(string ns)
    {
        var ids = await AnalyzerRunner.IdsAsync($"namespace {ns} {{ public class Pricing {{ }} }}", assemblyName: "Shop.Api");

        Assert.Empty(ids);
    }

    [Fact]
    public async Task Analyze_WithGlobalNamespace_ReportsNothing()
    {
        var ids = await AnalyzerRunner.IdsAsync("public class Pricing { }", assemblyName: "Shop.Api");

        Assert.Empty(ids);
    }

    [Theory]
    [InlineData("Shop.Shared")]
    [InlineData("Shop.SharedKernel")]
    [InlineData("Shop.Api.Tests")]
    [InlineData("Shop.IntegrationTests")]
    public async Task Analyze_WithExemptAssemblyName_ReportsNothing(string assemblyName)
    {
        var ids = await AnalyzerRunner.IdsAsync("namespace Shop.Services { public class Pricing { } }", assemblyName: assemblyName);

        Assert.Empty(ids);
    }

    [Fact]
    public async Task Analyze_WithSeverityConfiguredNone_ReportsNothing()
    {
        var source = "namespace Shop.Services { public class Pricing { } }";

        var ids = await AnalyzerRunner.IdsAsync(source, assemblyName: "Shop.Api", dlz0005: ReportDiagnostic.Suppress);

        Assert.Empty(ids);
    }

    [Fact]
    public async Task Analyze_WithAutoGeneratedFile_ReportsNothing()
    {
        var source = "// <auto-generated/>\nnamespace Shop.Services { public class Pricing { } }";

        var ids = await AnalyzerRunner.IdsAsync(source, assemblyName: "Shop.Api");

        Assert.Empty(ids);
    }
}
