using Microsoft.CodeAnalysis;

namespace Dloizides.Analyzers.Tests;

public class NoCommentsAnalyzerTests
{
    private const string Dlz0001 = "DLZ0001";
    private const string PragmaDirective = "#pragma";
    private const string LineCommentMarker = "//";

    [Fact]
    public async Task LineComment_InsideMethod_ReportsDlz0001()
    {
        var ids = await AnalyzerRunner.IdsAsync("public class A { public void M() {\n// skip the ETSS client\n} }");

        Assert.Equal(new[] { Dlz0001 }, ids);
    }

    [Fact]
    public async Task BlockComment_ReportsDlz0001()
    {
        var ids = await AnalyzerRunner.IdsAsync("/* block */\npublic class A { }");

        Assert.Equal(new[] { Dlz0001 }, ids);
    }

    [Fact]
    public async Task TrailingComment_ReportsDlz0001()
    {
        var ids = await AnalyzerRunner.IdsAsync($"public class A {{ public int X = 1; {LineCommentMarker} per EMS-1234\n}}");

        Assert.Equal(new[] { Dlz0001 }, ids);
    }

    [Fact]
    public async Task FourSlashComment_IsNotADocComment_ReportsDlz0001()
    {
        var ids = await AnalyzerRunner.IdsAsync("public class A {\n//// old code\n}");

        Assert.Equal(new[] { Dlz0001 }, ids);
    }

    [Fact]
    public async Task ToolDirectives_AreNotReported()
    {
        var source = $"{PragmaDirective} warning disable CS0168\n// ReSharper disable once UnusedMember.Global\npublic class A {{ }}\n{PragmaDirective} warning restore CS0168";

        var ids = await AnalyzerRunner.IdsAsync(source);

        Assert.Empty(ids);
    }

    [Theory]
    [InlineData(DocumentationMode.Parse)]
    [InlineData(DocumentationMode.None)]
    public async Task PublicDocComment_IsNotReportedAsAComment(DocumentationMode mode)
    {
        var ids = await AnalyzerRunner.IdsAsync("/// <summary>Prices a menu.</summary>\npublic class A { }", mode: mode);

        Assert.Empty(ids);
    }

    [Theory]
    [InlineData("src/Data/Migrations/20260101_Init.cs")]
    [InlineData("src\\Data\\Migrations\\20260101_Init.cs")]
    [InlineData("src/Data/Model.g.cs")]
    [InlineData("src/Forms/Form1.Designer.cs")]
    public async Task GeneratedOrMigrationFile_IsSkipped(string path)
    {
        var ids = await AnalyzerRunner.IdsAsync("// generated note\npublic class A { }", path);

        Assert.Empty(ids);
    }

    [Fact]
    public async Task AutoGeneratedHeader_SkipsTheFile()
    {
        var ids = await AnalyzerRunner.IdsAsync("// <auto-generated/>\n// other note\npublic class A { }");

        Assert.Empty(ids);
    }
}
